// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/simple-example.proto

package simple_example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Simple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsSimple      bool                   `protobuf:"varint,2,opt,name=is_simple,json=isSimple,proto3" json:"is_simple,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SampleLists   []int32                `protobuf:"varint,4,rep,packed,name=sample_lists,json=sampleLists,proto3" json:"sample_lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Simple) Reset() {
	*x = Simple{}
	mi := &file_proto_simple_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Simple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Simple) ProtoMessage() {}

func (x *Simple) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Simple.ProtoReflect.Descriptor instead.
func (*Simple) Descriptor() ([]byte, []int) {
	return file_proto_simple_example_proto_rawDescGZIP(), []int{0}
}

func (x *Simple) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Simple) GetIsSimple() bool {
	if x != nil {
		return x.IsSimple
	}
	return false
}

func (x *Simple) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Simple) GetSampleLists() []int32 {
	if x != nil {
		return x.SampleLists
	}
	return nil
}

var File_proto_simple_example_proto protoreflect.FileDescriptor

const file_proto_simple_example_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/simple-example.proto\x12\x0esimple.example\"l\n" +
	"\x06Simple\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tis_simple\x18\x02 \x01(\bR\bisSimple\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fsample_lists\x18\x04 \x03(\x05R\vsampleListsB9Z7github.com/nelson-araujo/na-sand/go/grpc/simple-exampleb\x06proto3"

var (
	file_proto_simple_example_proto_rawDescOnce sync.Once
	file_proto_simple_example_proto_rawDescData []byte
)

func file_proto_simple_example_proto_rawDescGZIP() []byte {
	file_proto_simple_example_proto_rawDescOnce.Do(func() {
		file_proto_simple_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simple_example_proto_rawDesc), len(file_proto_simple_example_proto_rawDesc)))
	})
	return file_proto_simple_example_proto_rawDescData
}

var file_proto_simple_example_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_simple_example_proto_goTypes = []any{
	(*Simple)(nil), // 0: simple.example.Simple
}
var file_proto_simple_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_simple_example_proto_init() }
func file_proto_simple_example_proto_init() {
	if File_proto_simple_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simple_example_proto_rawDesc), len(file_proto_simple_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_simple_example_proto_goTypes,
		DependencyIndexes: file_proto_simple_example_proto_depIdxs,
		MessageInfos:      file_proto_simple_example_proto_msgTypes,
	}.Build()
	File_proto_simple_example_proto = out.File
	file_proto_simple_example_proto_goTypes = nil
	file_proto_simple_example_proto_depIdxs = nil
}
