// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/client-server-example.proto

package client_server_example

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientStatusResponseService_ClientStatusResponse_FullMethodName = "/client.server.example.clientStatusResponseService/clientStatusResponse"
)

// ClientStatusResponseServiceClient is the client API for ClientStatusResponseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Client Status Response Sevice
type ClientStatusResponseServiceClient interface {
	ClientStatusResponse(ctx context.Context, in *ClientStatusRequestMessage, opts ...grpc.CallOption) (*ClientStatusResponseMessage, error)
}

type clientStatusResponseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientStatusResponseServiceClient(cc grpc.ClientConnInterface) ClientStatusResponseServiceClient {
	return &clientStatusResponseServiceClient{cc}
}

func (c *clientStatusResponseServiceClient) ClientStatusResponse(ctx context.Context, in *ClientStatusRequestMessage, opts ...grpc.CallOption) (*ClientStatusResponseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientStatusResponseMessage)
	err := c.cc.Invoke(ctx, ClientStatusResponseService_ClientStatusResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientStatusResponseServiceServer is the server API for ClientStatusResponseService service.
// All implementations must embed UnimplementedClientStatusResponseServiceServer
// for forward compatibility.
//
// Client Status Response Sevice
type ClientStatusResponseServiceServer interface {
	ClientStatusResponse(context.Context, *ClientStatusRequestMessage) (*ClientStatusResponseMessage, error)
	mustEmbedUnimplementedClientStatusResponseServiceServer()
}

// UnimplementedClientStatusResponseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientStatusResponseServiceServer struct{}

func (UnimplementedClientStatusResponseServiceServer) ClientStatusResponse(context.Context, *ClientStatusRequestMessage) (*ClientStatusResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientStatusResponse not implemented")
}
func (UnimplementedClientStatusResponseServiceServer) mustEmbedUnimplementedClientStatusResponseServiceServer() {
}
func (UnimplementedClientStatusResponseServiceServer) testEmbeddedByValue() {}

// UnsafeClientStatusResponseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientStatusResponseServiceServer will
// result in compilation errors.
type UnsafeClientStatusResponseServiceServer interface {
	mustEmbedUnimplementedClientStatusResponseServiceServer()
}

func RegisterClientStatusResponseServiceServer(s grpc.ServiceRegistrar, srv ClientStatusResponseServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientStatusResponseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientStatusResponseService_ServiceDesc, srv)
}

func _ClientStatusResponseService_ClientStatusResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientStatusRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientStatusResponseServiceServer).ClientStatusResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientStatusResponseService_ClientStatusResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientStatusResponseServiceServer).ClientStatusResponse(ctx, req.(*ClientStatusRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientStatusResponseService_ServiceDesc is the grpc.ServiceDesc for ClientStatusResponseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientStatusResponseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client.server.example.clientStatusResponseService",
	HandlerType: (*ClientStatusResponseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "clientStatusResponse",
			Handler:    _ClientStatusResponseService_ClientStatusResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/client-server-example.proto",
}
