syntax = "proto3";

package client.server.example;

option go_package = "github.com/nelson-araujo/na-sand/go/grpc/client-server-example";

/* Client Status Request Message
 * 
*/
message StatusRequestMessage {
  string MsgDatetimeUtc = 1; // TODO: Convert to google.protobuf.Timestamp

  // Client fields
  bool GetClientStatus = 100;
  
  // Device fields
  bool GetDeviceStatus = 200;
  string DeviceName = 201;
}

/* Client Status Response Message
 *
*/
message StatusResponseMessage {
  string MsgDatetimeUtc= 1; // TODO: convert to google.protobuf.Timestamp
  
  // Client fields
  string ClientName = 100;
  string ClientIanaTimezone = 101;
  uint32 ClientUptimeMinutes = 102;
  uint32 ClientCpuUse = 103;
  uint32 Client_MemoryUse = 104;
  uint32 ClientDiskUse = 105;
  uint32 ClientNetUse = 106;
  repeated string ClientStatusMessages = 107; // Status messages such as warnings and errors

  // Device fields
  string DeviceName = 200;
  string DeviceIanaTimezone = 201;
  uint32 DeviceUptimeMinutes = 202;
  uint32 DeviceCpuUse = 203;
  uint32 DeviceMemoryUse = 204;
  uint32 DeviceDiskUse = 205;
  uint32 DeviceNetUse = 206;
  repeated string DeviceStatusMessages = 207; // Status messages such as warnings and errors
}

/* Client Status Response Service
 *
*/
service StatusService {
  rpc StatusResponse(StatusRequestMessage) returns(StatusResponseMessage);
}
