// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/client-server-example.proto

package client_server_example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client Status Request Message
type ClientStatusRequestMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgDatetimeUtc string                 `protobuf:"bytes,1,opt,name=msg_datetime_utc,json=msgDatetimeUtc,proto3" json:"msg_datetime_utc,omitempty"` // TODO: Convert to google.protobuf.Timestamp
	// Client fields
	GetClientStatus bool `protobuf:"varint,100,opt,name=get_client_status,json=getClientStatus,proto3" json:"get_client_status,omitempty"`
	// Device fields
	GetDeviceSatus bool   `protobuf:"varint,200,opt,name=get_device_satus,json=getDeviceSatus,proto3" json:"get_device_satus,omitempty"`
	DeviceName     string `protobuf:"bytes,201,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientStatusRequestMessage) Reset() {
	*x = ClientStatusRequestMessage{}
	mi := &file_proto_client_server_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStatusRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStatusRequestMessage) ProtoMessage() {}

func (x *ClientStatusRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_server_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStatusRequestMessage.ProtoReflect.Descriptor instead.
func (*ClientStatusRequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_client_server_example_proto_rawDescGZIP(), []int{0}
}

func (x *ClientStatusRequestMessage) GetMsgDatetimeUtc() string {
	if x != nil {
		return x.MsgDatetimeUtc
	}
	return ""
}

func (x *ClientStatusRequestMessage) GetGetClientStatus() bool {
	if x != nil {
		return x.GetClientStatus
	}
	return false
}

func (x *ClientStatusRequestMessage) GetGetDeviceSatus() bool {
	if x != nil {
		return x.GetDeviceSatus
	}
	return false
}

func (x *ClientStatusRequestMessage) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

// Client Status Response Message
type ClientStatusResponseMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgDatetimeUtc string                 `protobuf:"bytes,1,opt,name=msg_datetime_utc,json=msgDatetimeUtc,proto3" json:"msg_datetime_utc,omitempty"` // TODO: convert to google.protobuf.Timestamp
	// Client fields
	ClientName           string   `protobuf:"bytes,100,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientIanaTimezone   string   `protobuf:"bytes,101,opt,name=client_iana_timezone,json=clientIanaTimezone,proto3" json:"client_iana_timezone,omitempty"`
	ClientUptimeMinutes  uint32   `protobuf:"varint,102,opt,name=client_uptime_minutes,json=clientUptimeMinutes,proto3" json:"client_uptime_minutes,omitempty"`
	ClientCpuUse         uint32   `protobuf:"varint,103,opt,name=client_cpu_use,json=clientCpuUse,proto3" json:"client_cpu_use,omitempty"`
	ClientMemoryUse      uint32   `protobuf:"varint,104,opt,name=client_memory_use,json=clientMemoryUse,proto3" json:"client_memory_use,omitempty"`
	ClientDiskUse        uint32   `protobuf:"varint,105,opt,name=client_disk_use,json=clientDiskUse,proto3" json:"client_disk_use,omitempty"`
	ClientNetUse         uint32   `protobuf:"varint,106,opt,name=client_net_use,json=clientNetUse,proto3" json:"client_net_use,omitempty"`
	ClientStatusMessages []string `protobuf:"bytes,107,rep,name=client_status_messages,json=clientStatusMessages,proto3" json:"client_status_messages,omitempty"` // Status messages such as warnings and errors
	// Device fields
	DeviceName           string   `protobuf:"bytes,200,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceIanaTimezone   string   `protobuf:"bytes,201,opt,name=device_iana_timezone,json=deviceIanaTimezone,proto3" json:"device_iana_timezone,omitempty"`
	DeviceUptimeMinutes  uint32   `protobuf:"varint,202,opt,name=device_uptime_minutes,json=deviceUptimeMinutes,proto3" json:"device_uptime_minutes,omitempty"`
	DeviceCpuUse         uint32   `protobuf:"varint,203,opt,name=device_cpu_use,json=deviceCpuUse,proto3" json:"device_cpu_use,omitempty"`
	DeviceMemoryUse      uint32   `protobuf:"varint,204,opt,name=device_memory_use,json=deviceMemoryUse,proto3" json:"device_memory_use,omitempty"`
	DeviceDiskUse        uint32   `protobuf:"varint,205,opt,name=device_disk_use,json=deviceDiskUse,proto3" json:"device_disk_use,omitempty"`
	DeviceNetUse         uint32   `protobuf:"varint,206,opt,name=device_net_use,json=deviceNetUse,proto3" json:"device_net_use,omitempty"`
	DeviceStatusMessages []string `protobuf:"bytes,207,rep,name=device_status_messages,json=deviceStatusMessages,proto3" json:"device_status_messages,omitempty"` // Status messages such as warnings and errors
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClientStatusResponseMessage) Reset() {
	*x = ClientStatusResponseMessage{}
	mi := &file_proto_client_server_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStatusResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStatusResponseMessage) ProtoMessage() {}

func (x *ClientStatusResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_server_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStatusResponseMessage.ProtoReflect.Descriptor instead.
func (*ClientStatusResponseMessage) Descriptor() ([]byte, []int) {
	return file_proto_client_server_example_proto_rawDescGZIP(), []int{1}
}

func (x *ClientStatusResponseMessage) GetMsgDatetimeUtc() string {
	if x != nil {
		return x.MsgDatetimeUtc
	}
	return ""
}

func (x *ClientStatusResponseMessage) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ClientStatusResponseMessage) GetClientIanaTimezone() string {
	if x != nil {
		return x.ClientIanaTimezone
	}
	return ""
}

func (x *ClientStatusResponseMessage) GetClientUptimeMinutes() uint32 {
	if x != nil {
		return x.ClientUptimeMinutes
	}
	return 0
}

func (x *ClientStatusResponseMessage) GetClientCpuUse() uint32 {
	if x != nil {
		return x.ClientCpuUse
	}
	return 0
}

func (x *ClientStatusResponseMessage) GetClientMemoryUse() uint32 {
	if x != nil {
		return x.ClientMemoryUse
	}
	return 0
}

func (x *ClientStatusResponseMessage) GetClientDiskUse() uint32 {
	if x != nil {
		return x.ClientDiskUse
	}
	return 0
}

func (x *ClientStatusResponseMessage) GetClientNetUse() uint32 {
	if x != nil {
		return x.ClientNetUse
	}
	return 0
}

func (x *ClientStatusResponseMessage) GetClientStatusMessages() []string {
	if x != nil {
		return x.ClientStatusMessages
	}
	return nil
}

func (x *ClientStatusResponseMessage) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *ClientStatusResponseMessage) GetDeviceIanaTimezone() string {
	if x != nil {
		return x.DeviceIanaTimezone
	}
	return ""
}

func (x *ClientStatusResponseMessage) GetDeviceUptimeMinutes() uint32 {
	if x != nil {
		return x.DeviceUptimeMinutes
	}
	return 0
}

func (x *ClientStatusResponseMessage) GetDeviceCpuUse() uint32 {
	if x != nil {
		return x.DeviceCpuUse
	}
	return 0
}

func (x *ClientStatusResponseMessage) GetDeviceMemoryUse() uint32 {
	if x != nil {
		return x.DeviceMemoryUse
	}
	return 0
}

func (x *ClientStatusResponseMessage) GetDeviceDiskUse() uint32 {
	if x != nil {
		return x.DeviceDiskUse
	}
	return 0
}

func (x *ClientStatusResponseMessage) GetDeviceNetUse() uint32 {
	if x != nil {
		return x.DeviceNetUse
	}
	return 0
}

func (x *ClientStatusResponseMessage) GetDeviceStatusMessages() []string {
	if x != nil {
		return x.DeviceStatusMessages
	}
	return nil
}

var File_proto_client_server_example_proto protoreflect.FileDescriptor

const file_proto_client_server_example_proto_rawDesc = "" +
	"\n" +
	"!proto/client-server-example.proto\x12\x15client.server.example\"\xbf\x01\n" +
	"\x1aclientStatusRequestMessage\x12(\n" +
	"\x10msg_datetime_utc\x18\x01 \x01(\tR\x0emsgDatetimeUtc\x12*\n" +
	"\x11get_client_status\x18d \x01(\bR\x0fgetClientStatus\x12)\n" +
	"\x10get_device_satus\x18\xc8\x01 \x01(\bR\x0egetDeviceSatus\x12 \n" +
	"\vdevice_name\x18\xc9\x01 \x01(\tR\n" +
	"deviceName\"\x89\x06\n" +
	"\x1bclientStatusResponseMessage\x12(\n" +
	"\x10msg_datetime_utc\x18\x01 \x01(\tR\x0emsgDatetimeUtc\x12\x1f\n" +
	"\vclient_name\x18d \x01(\tR\n" +
	"clientName\x120\n" +
	"\x14client_iana_timezone\x18e \x01(\tR\x12clientIanaTimezone\x122\n" +
	"\x15client_uptime_minutes\x18f \x01(\rR\x13clientUptimeMinutes\x12$\n" +
	"\x0eclient_cpu_use\x18g \x01(\rR\fclientCpuUse\x12*\n" +
	"\x11client_memory_use\x18h \x01(\rR\x0fclientMemoryUse\x12&\n" +
	"\x0fclient_disk_use\x18i \x01(\rR\rclientDiskUse\x12$\n" +
	"\x0eclient_net_use\x18j \x01(\rR\fclientNetUse\x124\n" +
	"\x16client_status_messages\x18k \x03(\tR\x14clientStatusMessages\x12 \n" +
	"\vdevice_name\x18\xc8\x01 \x01(\tR\n" +
	"deviceName\x121\n" +
	"\x14device_iana_timezone\x18\xc9\x01 \x01(\tR\x12deviceIanaTimezone\x123\n" +
	"\x15device_uptime_minutes\x18\xca\x01 \x01(\rR\x13deviceUptimeMinutes\x12%\n" +
	"\x0edevice_cpu_use\x18\xcb\x01 \x01(\rR\fdeviceCpuUse\x12+\n" +
	"\x11device_memory_use\x18\xcc\x01 \x01(\rR\x0fdeviceMemoryUse\x12'\n" +
	"\x0fdevice_disk_use\x18\xcd\x01 \x01(\rR\rdeviceDiskUse\x12%\n" +
	"\x0edevice_net_use\x18\xce\x01 \x01(\rR\fdeviceNetUse\x125\n" +
	"\x16device_status_messages\x18\xcf\x01 \x03(\tR\x14deviceStatusMessages2\x9c\x01\n" +
	"\x1bclientStatusResponseService\x12}\n" +
	"\x14clientStatusResponse\x121.client.server.example.clientStatusRequestMessage\x1a2.client.server.example.clientStatusResponseMessageB@Z>github.com/nelson-araujo/na-sand/go/grpc/client-server-exampleb\x06proto3"

var (
	file_proto_client_server_example_proto_rawDescOnce sync.Once
	file_proto_client_server_example_proto_rawDescData []byte
)

func file_proto_client_server_example_proto_rawDescGZIP() []byte {
	file_proto_client_server_example_proto_rawDescOnce.Do(func() {
		file_proto_client_server_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_client_server_example_proto_rawDesc), len(file_proto_client_server_example_proto_rawDesc)))
	})
	return file_proto_client_server_example_proto_rawDescData
}

var file_proto_client_server_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_client_server_example_proto_goTypes = []any{
	(*ClientStatusRequestMessage)(nil),  // 0: client.server.example.clientStatusRequestMessage
	(*ClientStatusResponseMessage)(nil), // 1: client.server.example.clientStatusResponseMessage
}
var file_proto_client_server_example_proto_depIdxs = []int32{
	0, // 0: client.server.example.clientStatusResponseService.clientStatusResponse:input_type -> client.server.example.clientStatusRequestMessage
	1, // 1: client.server.example.clientStatusResponseService.clientStatusResponse:output_type -> client.server.example.clientStatusResponseMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_client_server_example_proto_init() }
func file_proto_client_server_example_proto_init() {
	if File_proto_client_server_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_client_server_example_proto_rawDesc), len(file_proto_client_server_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_client_server_example_proto_goTypes,
		DependencyIndexes: file_proto_client_server_example_proto_depIdxs,
		MessageInfos:      file_proto_client_server_example_proto_msgTypes,
	}.Build()
	File_proto_client_server_example_proto = out.File
	file_proto_client_server_example_proto_goTypes = nil
	file_proto_client_server_example_proto_depIdxs = nil
}
