// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/client_server_example.proto

package client_server_example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client Status Request Message
type StatusRequestMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgDatetimeUtc string                 `protobuf:"bytes,1,opt,name=MsgDatetimeUtc,proto3" json:"MsgDatetimeUtc,omitempty"` // TODO: Convert to google.protobuf.Timestamp
	// Client fields
	GetClientStatus bool `protobuf:"varint,100,opt,name=GetClientStatus,proto3" json:"GetClientStatus,omitempty"`
	// Device fields
	GetDeviceStatus bool   `protobuf:"varint,200,opt,name=GetDeviceStatus,proto3" json:"GetDeviceStatus,omitempty"`
	DeviceName      string `protobuf:"bytes,201,opt,name=DeviceName,proto3" json:"DeviceName,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusRequestMessage) Reset() {
	*x = StatusRequestMessage{}
	mi := &file_proto_client_server_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequestMessage) ProtoMessage() {}

func (x *StatusRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_server_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequestMessage.ProtoReflect.Descriptor instead.
func (*StatusRequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_client_server_example_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequestMessage) GetMsgDatetimeUtc() string {
	if x != nil {
		return x.MsgDatetimeUtc
	}
	return ""
}

func (x *StatusRequestMessage) GetGetClientStatus() bool {
	if x != nil {
		return x.GetClientStatus
	}
	return false
}

func (x *StatusRequestMessage) GetGetDeviceStatus() bool {
	if x != nil {
		return x.GetDeviceStatus
	}
	return false
}

func (x *StatusRequestMessage) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

// Client Status Response Message
type StatusResponseMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgDatetimeUtc string                 `protobuf:"bytes,1,opt,name=MsgDatetimeUtc,proto3" json:"MsgDatetimeUtc,omitempty"` // TODO: convert to google.protobuf.Timestamp
	// Client fields
	ClientName           string   `protobuf:"bytes,100,opt,name=ClientName,proto3" json:"ClientName,omitempty"`
	ClientIanaTimezone   string   `protobuf:"bytes,101,opt,name=ClientIanaTimezone,proto3" json:"ClientIanaTimezone,omitempty"`
	ClientUptimeMinutes  uint32   `protobuf:"varint,102,opt,name=ClientUptimeMinutes,proto3" json:"ClientUptimeMinutes,omitempty"`
	ClientCpuUse         uint32   `protobuf:"varint,103,opt,name=ClientCpuUse,proto3" json:"ClientCpuUse,omitempty"`
	Client_MemoryUse     uint32   `protobuf:"varint,104,opt,name=Client_MemoryUse,json=ClientMemoryUse,proto3" json:"Client_MemoryUse,omitempty"`
	ClientDiskUse        uint32   `protobuf:"varint,105,opt,name=ClientDiskUse,proto3" json:"ClientDiskUse,omitempty"`
	ClientNetUse         uint32   `protobuf:"varint,106,opt,name=ClientNetUse,proto3" json:"ClientNetUse,omitempty"`
	ClientStatusMessages []string `protobuf:"bytes,107,rep,name=ClientStatusMessages,proto3" json:"ClientStatusMessages,omitempty"` // Status messages such as warnings and errors
	// Device fields
	DeviceName           string   `protobuf:"bytes,200,opt,name=DeviceName,proto3" json:"DeviceName,omitempty"`
	DeviceIanaTimezone   string   `protobuf:"bytes,201,opt,name=DeviceIanaTimezone,proto3" json:"DeviceIanaTimezone,omitempty"`
	DeviceUptimeMinutes  uint32   `protobuf:"varint,202,opt,name=DeviceUptimeMinutes,proto3" json:"DeviceUptimeMinutes,omitempty"`
	DeviceCpuUse         uint32   `protobuf:"varint,203,opt,name=DeviceCpuUse,proto3" json:"DeviceCpuUse,omitempty"`
	DeviceMemoryUse      uint32   `protobuf:"varint,204,opt,name=DeviceMemoryUse,proto3" json:"DeviceMemoryUse,omitempty"`
	DeviceDiskUse        uint32   `protobuf:"varint,205,opt,name=DeviceDiskUse,proto3" json:"DeviceDiskUse,omitempty"`
	DeviceNetUse         uint32   `protobuf:"varint,206,opt,name=DeviceNetUse,proto3" json:"DeviceNetUse,omitempty"`
	DeviceStatusMessages []string `protobuf:"bytes,207,rep,name=DeviceStatusMessages,proto3" json:"DeviceStatusMessages,omitempty"` // Status messages such as warnings and errors
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StatusResponseMessage) Reset() {
	*x = StatusResponseMessage{}
	mi := &file_proto_client_server_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponseMessage) ProtoMessage() {}

func (x *StatusResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_server_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponseMessage.ProtoReflect.Descriptor instead.
func (*StatusResponseMessage) Descriptor() ([]byte, []int) {
	return file_proto_client_server_example_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponseMessage) GetMsgDatetimeUtc() string {
	if x != nil {
		return x.MsgDatetimeUtc
	}
	return ""
}

func (x *StatusResponseMessage) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *StatusResponseMessage) GetClientIanaTimezone() string {
	if x != nil {
		return x.ClientIanaTimezone
	}
	return ""
}

func (x *StatusResponseMessage) GetClientUptimeMinutes() uint32 {
	if x != nil {
		return x.ClientUptimeMinutes
	}
	return 0
}

func (x *StatusResponseMessage) GetClientCpuUse() uint32 {
	if x != nil {
		return x.ClientCpuUse
	}
	return 0
}

func (x *StatusResponseMessage) GetClient_MemoryUse() uint32 {
	if x != nil {
		return x.Client_MemoryUse
	}
	return 0
}

func (x *StatusResponseMessage) GetClientDiskUse() uint32 {
	if x != nil {
		return x.ClientDiskUse
	}
	return 0
}

func (x *StatusResponseMessage) GetClientNetUse() uint32 {
	if x != nil {
		return x.ClientNetUse
	}
	return 0
}

func (x *StatusResponseMessage) GetClientStatusMessages() []string {
	if x != nil {
		return x.ClientStatusMessages
	}
	return nil
}

func (x *StatusResponseMessage) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *StatusResponseMessage) GetDeviceIanaTimezone() string {
	if x != nil {
		return x.DeviceIanaTimezone
	}
	return ""
}

func (x *StatusResponseMessage) GetDeviceUptimeMinutes() uint32 {
	if x != nil {
		return x.DeviceUptimeMinutes
	}
	return 0
}

func (x *StatusResponseMessage) GetDeviceCpuUse() uint32 {
	if x != nil {
		return x.DeviceCpuUse
	}
	return 0
}

func (x *StatusResponseMessage) GetDeviceMemoryUse() uint32 {
	if x != nil {
		return x.DeviceMemoryUse
	}
	return 0
}

func (x *StatusResponseMessage) GetDeviceDiskUse() uint32 {
	if x != nil {
		return x.DeviceDiskUse
	}
	return 0
}

func (x *StatusResponseMessage) GetDeviceNetUse() uint32 {
	if x != nil {
		return x.DeviceNetUse
	}
	return 0
}

func (x *StatusResponseMessage) GetDeviceStatusMessages() []string {
	if x != nil {
		return x.DeviceStatusMessages
	}
	return nil
}

var File_proto_client_server_example_proto protoreflect.FileDescriptor

const file_proto_client_server_example_proto_rawDesc = "" +
	"\n" +
	"!proto/client_server_example.proto\x12\x15client.server.example\"\xb4\x01\n" +
	"\x14StatusRequestMessage\x12&\n" +
	"\x0eMsgDatetimeUtc\x18\x01 \x01(\tR\x0eMsgDatetimeUtc\x12(\n" +
	"\x0fGetClientStatus\x18d \x01(\bR\x0fGetClientStatus\x12)\n" +
	"\x0fGetDeviceStatus\x18\xc8\x01 \x01(\bR\x0fGetDeviceStatus\x12\x1f\n" +
	"\n" +
	"DeviceName\x18\xc9\x01 \x01(\tR\n" +
	"DeviceName\"\xe4\x05\n" +
	"\x15StatusResponseMessage\x12&\n" +
	"\x0eMsgDatetimeUtc\x18\x01 \x01(\tR\x0eMsgDatetimeUtc\x12\x1e\n" +
	"\n" +
	"ClientName\x18d \x01(\tR\n" +
	"ClientName\x12.\n" +
	"\x12ClientIanaTimezone\x18e \x01(\tR\x12ClientIanaTimezone\x120\n" +
	"\x13ClientUptimeMinutes\x18f \x01(\rR\x13ClientUptimeMinutes\x12\"\n" +
	"\fClientCpuUse\x18g \x01(\rR\fClientCpuUse\x12)\n" +
	"\x10Client_MemoryUse\x18h \x01(\rR\x0fClientMemoryUse\x12$\n" +
	"\rClientDiskUse\x18i \x01(\rR\rClientDiskUse\x12\"\n" +
	"\fClientNetUse\x18j \x01(\rR\fClientNetUse\x122\n" +
	"\x14ClientStatusMessages\x18k \x03(\tR\x14ClientStatusMessages\x12\x1f\n" +
	"\n" +
	"DeviceName\x18\xc8\x01 \x01(\tR\n" +
	"DeviceName\x12/\n" +
	"\x12DeviceIanaTimezone\x18\xc9\x01 \x01(\tR\x12DeviceIanaTimezone\x121\n" +
	"\x13DeviceUptimeMinutes\x18\xca\x01 \x01(\rR\x13DeviceUptimeMinutes\x12#\n" +
	"\fDeviceCpuUse\x18\xcb\x01 \x01(\rR\fDeviceCpuUse\x12)\n" +
	"\x0fDeviceMemoryUse\x18\xcc\x01 \x01(\rR\x0fDeviceMemoryUse\x12%\n" +
	"\rDeviceDiskUse\x18\xcd\x01 \x01(\rR\rDeviceDiskUse\x12#\n" +
	"\fDeviceNetUse\x18\xce\x01 \x01(\rR\fDeviceNetUse\x123\n" +
	"\x14DeviceStatusMessages\x18\xcf\x01 \x03(\tR\x14DeviceStatusMessages2|\n" +
	"\rStatusService\x12k\n" +
	"\x0eStatusResponse\x12+.client.server.example.StatusRequestMessage\x1a,.client.server.example.StatusResponseMessageB@Z>github.com/nelson-araujo/na-sand/go/grpc/client-server-exampleb\x06proto3"

var (
	file_proto_client_server_example_proto_rawDescOnce sync.Once
	file_proto_client_server_example_proto_rawDescData []byte
)

func file_proto_client_server_example_proto_rawDescGZIP() []byte {
	file_proto_client_server_example_proto_rawDescOnce.Do(func() {
		file_proto_client_server_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_client_server_example_proto_rawDesc), len(file_proto_client_server_example_proto_rawDesc)))
	})
	return file_proto_client_server_example_proto_rawDescData
}

var file_proto_client_server_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_client_server_example_proto_goTypes = []any{
	(*StatusRequestMessage)(nil),  // 0: client.server.example.StatusRequestMessage
	(*StatusResponseMessage)(nil), // 1: client.server.example.StatusResponseMessage
}
var file_proto_client_server_example_proto_depIdxs = []int32{
	0, // 0: client.server.example.StatusService.StatusResponse:input_type -> client.server.example.StatusRequestMessage
	1, // 1: client.server.example.StatusService.StatusResponse:output_type -> client.server.example.StatusResponseMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_client_server_example_proto_init() }
func file_proto_client_server_example_proto_init() {
	if File_proto_client_server_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_client_server_example_proto_rawDesc), len(file_proto_client_server_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_client_server_example_proto_goTypes,
		DependencyIndexes: file_proto_client_server_example_proto_depIdxs,
		MessageInfos:      file_proto_client_server_example_proto_msgTypes,
	}.Build()
	File_proto_client_server_example_proto = out.File
	file_proto_client_server_example_proto_goTypes = nil
	file_proto_client_server_example_proto_depIdxs = nil
}
